import Head from 'next/head'

export default function Dashboard() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Hello world</div>
      </main>
    </>
  )
}
