import Head from 'next/head'
import { signIn } from 'next-auth/react'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>
          <button
            className="btn btn-primary"
            onClick={() =>
              signIn(undefined, {
                callbackUrl: '/dashboard'
              })
            }
          >
            Sign In
          </button>
        </div>
      </main>
    </>
  )
}
